### PR TITLE
Fixed an issue where some menu items didn't get correctly deactivated

### PR DESCRIPTION
**Pull request by asermax**
For some reason, the items/actions you added in the last version wouldn't deactivate (at least when first opening rhythmbox).
I replaced the loop over the widgets and directly deactivated the root menu.

### CODE REVIEW

**Comment by afrancoto** [comment]
Great! I wrote all those lines because `get_widget("/MenuBar/WebMenu").set_sensitive(False)' didn't want to work, I couldn't figured out why so I took the easy way out :P
Now it's perfect! :D

**Comment by asermax** [comment]
I wonder why it wouldn't it work xD welp, at least it works now :F

**Comment by afrancoto** [comment]
Wait! Again, it doesn't work for me:
No other plugin activated
I launch rhythmbox: no song is playing
The Web menu is visible but doesn't respond at click
When I click on "Help" (the menu at his left) and then move the cursor over the Web Menu it works as if it isn't deactivated!
When I click on one item I get the same old error:

<pre>
Traceback (most recent call last):
  File "/home/andrea/.local/share/rhythmbox/plugins/WebMenu/WebMenu.py", line 416, in search_on_youtube
    metadata=self.get_metadata(shell, context) #Calls "get_metadata"
  File "/home/andrea/.local/share/rhythmbox/plugins/WebMenu/WebMenu.py", line 405, in get_metadata
    playing_title = self.playing_entry.get_string(RB.RhythmDBPropType.TITLE)
AttributeError: 'NoneType' object has no attribute 'get_string'
</pre>


Screenshot: http://s7.postimage.org/bwj1hdke3/Schermata_del_2012_08_19_21_06_17.png

**Comment by asermax** [comment]
Really weird. Could it be an Ubuntu specific bug? I use LMDE and can't reproduce that behavior.
Well, then it would be better to reimplement your solution, since it works in both cases.

**Comment by afrancoto** [comment]
I write it back, if you have the same problem again please let me know!

**Comment by asermax** [comment]
Fixed, the problem was that I hand't recompile the schema with the new options.
Sorry for the inconveniences :F

**Comment by afrancoto** [comment]
No problem! It's better to look for a non existing error than to ignore an existing one :D

**Pull request merged**
